###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-mall-member
    datasource:
      username: appuser
      password: appuser
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.2:3306/tcc?useUnicode=true&characterEncoding=UTF-8
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

####swagger相关配置
swagger:
  base-package: com.mall.jelly.member.service
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 该项目基于SpringCloud2.x构建微服务电商项目
  version: 1.1
  terms-of-service-url: www.baidu.com
