###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: app-mall-zuul
    datasource:
      username: appuser
      password: appuser
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.2:3306/tcc?useUnicode=true&characterEncoding=UTF-8
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

### 配置网关反向代理
zuul:
  routes:
    api-a:
     ### 以 /api-weixin/访问转发到微信服务
      path: /public/api-weixin/**
      serviceId: app-mall-weixin
    api-b:
        ### 以 /api-member/访问转发到会员服务
      path: /public/api-member/**
      serviceId: app-mall-member
